In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
superstore = pd.read_excel("./superstore.xlsx")

In [3]:
superstore.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9994 entries, 0 to 9993
Data columns (total 23 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Order ID            9994 non-null   object
 1   Order Date          9994 non-null   datetime64[ns]
 2   Ship Date           9994 non-null   datetime64[ns]
 3   Ship Mode           9994 non-null   object
 4   Customer ID         9994 non-null   object
 5   Customer Name       9994 non-null   object
 6   Segment             9994 non-null   object
 7   Sales Rep           9994 non-null   object
 8   Sales Team          9994 non-null   object
 9   Sales Team Manager  9994 non-null   object
 10  Location ID         9994 non-null   object
 11  City                9994 non-null   object
 12  State               9994 non-null   object
 13  Postal Code         9994 non-null   int64
 14  Region              9994 non-null   object
 15  Product ID          9994 non-null   object
 16  Category            9994 non-null   object
 17  Sub-Category        9994 non-null   object
 18  Product Name        9994 non-null   object
 19  Sales               9994 non-null   float64
 20  Quantity            9994 non-null   int64
 21  Discount            9994 non-null   float64
 22  Profit              9994 non-null   float64
dtypes: datetime64[ns](2), float64(3), int64(2), object(16)
memory usage: 1.8+ MB

In [4]:
superstore.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Sales Rep,Sales Team,Sales Team Manager,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,Organic,Organic,Organic,...,42420,South,"FUR-BO-10001798,Bush Somerset Collection Bookcase",Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,Organic,Organic,Organic,...,42420,South,"FUR-CH-10000454,Hon Deluxe Fabric Upholstered ...",Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,Steve Pepple,Bravo,Tracy Banks,...,90036,West,"OFF-LA-10000240,Self-Adhesive Address Labels f...",Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,Organic,Organic,Organic,...,33311,South,"FUR-TA-10000577,Bretford CR4500 Series Slim Re...",Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,Organic,Organic,Organic,...,33311,South,"OFF-ST-10000760,Eldon Fold 'N Roll Cart System",Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164

In [5]:
total_sales = superstore['Sales'].sum()

In [6]:
total_sales # total sales

2297200.8603000003

In [7]:
superstore.tail()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Sales Rep,Sales Team,Sales Team Manager,...,Postal Code,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit
9989,CA-2014-110422,2014-01-21,2014-01-23,Second Class,TB-21400,Tom Boeckenhauer,Consumer,Organic,Organic,Organic,...,33180,South,"FUR-FU-10001889,Ultra Door Pull Handle",Furniture,Furnishings,Ultra Door Pull Handle,25.248,3,0.2,4.1028
9990,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,Organic,Organic,Organic,...,92627,West,"FUR-FU-10000747,Tenex B1-RE Series Chair Mats ...",Furniture,Furnishings,Tenex B1-RE Series Chair Mats for Low Pile Car...,91.960,2,0.0,15.6332
9991,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,Organic,Organic,Organic,...,92627,West,"TEC-PH-10003645,Aastra 57i VoIP phone",Technology,Phones,Aastra 57i VoIP phone,258.576,2,0.2,19.3932
9992,CA-2017-121258,2017-02-26,2017-03-03,Standard Class,DB-13060,Dave Brooks,Consumer,Organic,Organic,Organic,...,92627,West,"OFF-PA-10004041,It's Hot Message Books with St...",Office Supplies,Paper,"It's Hot Message Books with Stickers, 2 3/4"" x 5""",29.600,4,0.0,13.3200
9993,CA-2017-119914,2017-05-04,2017-05-09,Second Class,CC-12220,Chris Cortes,Consumer,Organic,Organic,Organic,...,92683,West,"OFF-AP-10002684,Acco 7-Outlet Masterpiece Powe...",Office Supplies,Appliances,"Acco 7-Outlet Masterpiece Power Center, Wihtou...",243.160,2,0.0,72.9480

In [8]:
superstore.describe()

,Order Date,Ship Date,Postal Code,Sales,Quantity,Discount,Profit
count,9994,9994,9994.000000,9994.000000,9994.000000,9994.000000,9994.000000
mean,2016-04-30 00:07:12.259355648,2016-05-03 23:06:58.571142912,55190.379428,229.858001,3.789574,0.156203,28.656896
min,2014-01-03 00:00:00,2014-01-07 00:00:00,1040.000000,0.444000,1.000000,0.000000,-6599.978000
25%,2015-05-23 00:00:00,2015-05-27 00:00:00,23223.000000,17.280000,2.000000,0.000000,1.728750
50%,2016-06-26 00:00:00,2016-06-29 00:00:00,56430.500000,54.490000,3.000000,0.200000,8.666500
75%,2017-05-14 00:00:00,2017-05-18 00:00:00,90008.000000,209.940000,5.000000,0.200000,29.364000
max,2017-12-30 00:00:00,2018-01-05 00:00:00,99301.000000,22638.480000,14.000000,0.800000,8399.976000
std,NaN,NaN,32063.693350,623.245101,2.225110,0.206452,234.260108

In [9]:
total_profit = superstore["Profit"].sum() # total_profit
total_profit

286397.0216999999

In [10]:
superstore["Total Revenue"] = superstore["Sales"]*superstore["Quantity"]

In [11]:
superstore.head()

,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Sales Rep,Sales Team,Sales Team Manager,...,Region,Product ID,Category,Sub-Category,Product Name,Sales,Quantity,Discount,Profit,Total Revenue
0,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,Organic,Organic,Organic,...,South,"FUR-BO-10001798,Bush Somerset Collection Bookcase",Furniture,Bookcases,Bush Somerset Collection Bookcase,261.9600,2,0.00,41.9136,523.9200
1,CA-2016-152156,2016-11-08,2016-11-11,Second Class,CG-12520,Claire Gute,Consumer,Organic,Organic,Organic,...,South,"FUR-CH-10000454,Hon Deluxe Fabric Upholstered ...",Furniture,Chairs,"Hon Deluxe Fabric Upholstered Stacking Chairs,...",731.9400,3,0.00,219.5820,2195.8200
2,CA-2016-138688,2016-06-12,2016-06-16,Second Class,DV-13045,Darrin Van Huff,Corporate,Steve Pepple,Bravo,Tracy Banks,...,West,"OFF-LA-10000240,Self-Adhesive Address Labels f...",Office Supplies,Labels,Self-Adhesive Address Labels for Typewriters b...,14.6200,2,0.00,6.8714,29.2400
3,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,Organic,Organic,Organic,...,South,"FUR-TA-10000577,Bretford CR4500 Series Slim Re...",Furniture,Tables,Bretford CR4500 Series Slim Rectangular Table,957.5775,5,0.45,-383.0310,4787.8875
4,US-2015-108966,2015-10-11,2015-10-18,Standard Class,SO-20335,Sean O'Donnell,Consumer,Organic,Organic,Organic,...,South,"OFF-ST-10000760,Eldon Fold 'N Roll Cart System",Office Supplies,Storage,Eldon Fold 'N Roll Cart System,22.3680,2,0.20,2.5164,44.7360

In [12]:
total_revenue = superstore["Total Revenue"].sum()
total_revenue

11488062.0719

In [13]:
profit_margin = (total_profit/ total_revenue)*100
profit_margin

2.492996816238763

In [14]:
best_performing_quantity_segment = superstore.groupby('Segment')['Quantity'].sum()
best_performing_quantity_segment

Segment
Consumer       19521
Corporate      11608
Home Office     6744
Name: Quantity, dtype: int64

In [15]:
best_perfoming_sales_segment = superstore.groupby("Segment")["Sales"].sum()
best_perfoming_sales_segment

Segment
Consumer       1.161401e+06
Corporate      7.061464e+05
Home Office    4.296531e+05
Name: Sales, dtype: float64

In [16]:
profit_segment = superstore.groupby("Segment")["Profit"].sum()
profit_segment

Segment
Consumer       134119.2092
Corporate       91979.1340
Home Office     60298.6785
Name: Profit, dtype: float64

In [17]:
superstore["Segment"].nunique()

3

In [18]:
categories_quantity = superstore.groupby("Category")["Quantity"].sum()
categories_quantity

Category
Furniture           8028
Office Supplies    22906
Technology          6939
Name: Quantity, dtype: int64

In [19]:
categories_sales  = superstore.groupby("Category")["Sales"].sum()
categories_sales

Category
Furniture          741999.7953
Office Supplies    719047.0320
Technology         836154.0330
Name: Sales, dtype: float64

In [20]:
categories_profit  = superstore.groupby("Category")["Profit"].sum()
categories_profit

Category
Furniture           18451.2728
Office Supplies    122490.8008
Technology         145454.9481
Name: Profit, dtype: float64

In [21]:
subcategories_profit  =superstore.groupby("Sub-Category")["Profit"].sum().sort_values(ascending = False).to_frame()
subcategories_profit

                  Profit
Sub-Category
Copiers       55617.8249
Phones        44515.7306
Accessories   41936.6357
Paper         34053.5693
Binders       30221.7633
Chairs        26590.1663
Storage       21278.8264
Appliances    18138.0054
Furnishings   13059.1436
Envelopes      6964.1767
Art            6527.7870
Labels         5546.2540
Machines       3384.7569
Fasteners       949.5182
Supplies      -1189.0995
Bookcases     -3472.5560
Tables       -17725.4811

In [22]:
subcategories_profit.head(10)

                  Profit
Sub-Category
Copiers       55617.8249
Phones        44515.7306
Accessories   41936.6357
Paper         34053.5693
Binders       30221.7633
Chairs        26590.1663
Storage       21278.8264
Appliances    18138.0054
Furnishings   13059.1436
Envelopes      6964.1767

In [23]:
product_perfomance = superstore.groupby('Product Name')['Quantity'].sum().sort_values(ascending = False).to_frame()
product_perfomance

                                                    Quantity
Product Name
Staples                                                  215
Staple envelope                                          170
Easy-staple paper                                        150
Staples in misc. colors                                   86
KI Adjustable-Height Table                                74
...                                                      ...
Global Enterprise Series Seating Low-Back Swive...         1
Xerox 20                                                   1
Penpower WorldCard Pro Card Scanner                        1
Bush Saratoga Collection 5-Shelf Bookcase, Hano...         1
Boston 1900 Electric Pencil Sharpener                      1

[1850 rows x 1 columns]

In [24]:
product_perfomance.head(10)

                                                    Quantity
Product Name
Staples                                                  215
Staple envelope                                          170
Easy-staple paper                                        150
Staples in misc. colors                                   86
KI Adjustable-Height Table                                74
Avery Non-Stick Binders                                   71
Storex Dura Pro Binders                                   71
GBC Premium Transparent Covers with Diagonal Li...        67
Situations Contoured Folding Chairs, 4/Set                64
Staple-based wall hangings                                62

In [25]:
product_sales = superstore.groupby("Product Name")["Sales"].sum().sort_values(ascending=False).to_frame()
product_sales

                                                        Sales
Product Name
Canon imageCLASS 2200 Advanced Copier               61599.824
Fellowes PB500 Electric Punch Plastic Comb Bind...  27453.384
Cisco TelePresence System EX90 Videoconferencin...  22638.480
HON 5400 Series Task Chairs for Big and Tall        21870.576
GBC DocuBind TL300 Electric Binding System          19823.479
...                                                       ...
Avery Hi-Liter Pen Style Six-Color Fluorescent Set      7.700
Grip Seal Envelopes                                     7.072
Xerox 20                                                6.480
Avery 5                                                 5.760
Eureka Disposable Bags for Sanitaire Vibra Groo...      1.624

[1850 rows x 1 columns]

In [26]:
product_sales.head(10)

                                                        Sales
Product Name
Canon imageCLASS 2200 Advanced Copier               61599.824
Fellowes PB500 Electric Punch Plastic Comb Bind...  27453.384
Cisco TelePresence System EX90 Videoconferencin...  22638.480
HON 5400 Series Task Chairs for Big and Tall        21870.576
GBC DocuBind TL300 Electric Binding System          19823.479
GBC Ibimaster 500 Manual ProClick Binding System    19024.500
Hewlett Packard LaserJet 3310 Copier                18839.686
HP Designjet T520 Inkjet Large Format Printer -...  18374.895
GBC DocuBind P400 Electric Binding System           17965.068
High Speed Automatic Electric Letter Opener         17030.312

In [27]:
product_profit = superstore.groupby("Product Name")["Profit"].sum().sort_values(ascending=False).to_frame()
product_profit

                                                        Profit
Product Name
Canon imageCLASS 2200 Advanced Copier               25199.9280
Fellowes PB500 Electric Punch Plastic Comb Bind...   7753.0390
Hewlett Packard LaserJet 3310 Copier                 6983.8836
Canon PC1060 Personal Laser Copier                   4570.9347
HP Designjet T520 Inkjet Large Format Printer -...   4094.9766
...                                                        ...
Bush Advantage Collection Racetrack Conference ...  -1934.3976
Chromcraft Bull-Nose Wood Oval Conference Table...  -2876.1156
Cubify CubeX 3D Printer Triple Head Print           -3839.9904
Lexmark MX611dhe Monochrome Laser Printer           -4589.9730
Cubify CubeX 3D Printer Double Head Print           -8879.9704

[1850 rows x 1 columns]

In [28]:
product_profit.head(10)

                                                        Profit
Product Name
Canon imageCLASS 2200 Advanced Copier               25199.9280
Fellowes PB500 Electric Punch Plastic Comb Bind...   7753.0390
Hewlett Packard LaserJet 3310 Copier                 6983.8836
Canon PC1060 Personal Laser Copier                   4570.9347
HP Designjet T520 Inkjet Large Format Printer -...   4094.9766
Ativa V4110MDD Micro-Cut Shredder                    3772.9461
3D Systems Cube Printer, 2nd Generation, Magenta     3717.9714
Plantronics Savi W720 Multi-Device Wireless Hea...   3696.2820
Ibico EPK-21 Electric Binding System                 3345.2823
Zebra ZM400 Thermal Label Printer                    3343.5360